### ISSUE TITLE
Get "real" IP into CHN Server data

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#41]
Currently the IP address reflected in the CHN web app is for the docker IP seen by the honeypot. It would be nice to see the host IP address for ease of management.

**Comment by JesseBowling** [comment]
In next tagged release

**Comment by amerck** [comment]
Fixed with commits b6368eaad8678ae8a5284d5f34e4669cd2c10af8 and a711bf1642cef28596ddc4a20b39fefaceeb9473. There's no reliable way to detect the IP address of the host running docker at the moment. However, these changes will allow you to set the IP address via sysconfig prior to starting the container, or by later modifying the value in the CHN Server web interface.
