### ISSUE TITLE
Documentation of how to move SSH port for cowrie honeypots (Ubuntu)

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#45]
Would like documentation on how to move the default SSH port on Ubuntu so that Cowrie can be run on the traditional default port (22)

**Comment by kraigu** [comment]
Short version: edit /etc/ssh/sshd_config. Change Port from 22 to anything else. Restart sshd and connect to the new port to make sure it works, if you're ssh'ed in. *Then* disconnect your existing session. :) In your cowrie's docker-compose, have:
```
ports:
 - "22":"2222"
```
instead of the default "2222":"2222".

I can send a docs pull request tomorrow unless somebody beats me to it.

**Comment by kraigu** [comment]
I made a pull request for this, but I accidentally added it to a previous one I had for updating the Mac docs. Pull request #1 for the docs repo.

**Comment by JesseBowling** [comment]
Thank you! We have incorporated your information into the documentation, but no via the pull request (sorry about that!).
