### ISSUE TITLE
Filesystem Reorganization Needed

### ISSUE THREAD

**Issue by clcollins** [CommunityHoneyNetwork/CHN-Server#7]
Our current setup has the orchestration pieces mixed in with the server code; and all of it's thrown into /opt by default during the build.  Additionally, since we need the HPFeeds clone, it's ending up in /srv, and symlinked into /opt/hpfeeds because we can't clone into /opt directly.

This needs to be reorganized, across all projects, but specifically for this one, I'm proposing:

/opt/chnserver/deploy - orchestration code (docker & ansible stuff)
/opt/chnserver/server - server code
/opt/hpfeeds/hpfeeds - hpfeeds code (ideally also refactoring hpfeeds to have its own deploy dir)

This will require ansible variable updates, some path refactoring for the python stuff in /opt/server, and updates to the runit .run files for the chnserver stuff.

**Comment by drewstinnett** [comment]
What about instead of having a hard coded path against all OSes, we make it a real python module (setup.py, setuptools, etc).  We can specify in there which directories should be static, and python can then just dump it all to wherever it usually puts modules on the filesystem?

This would have the added benefit of auto installing the dependencies when the package is installed.

**Comment by JesseBowling** [comment]
Closing wontfix
